### ISSUE TITLE
дубль

### ISSUE THREAD

**Issue by Shur-AA** [aentin/qgis-course#11]
https://github.com/aentin/qgis-course/blob/d944696150471a35b25796f222e9fcdafef7184e/Ex06_Vectorization.Rmd#L209
я не повторяю 2 раза, не повторяю 2 раза...
![1](https://user-images.githubusercontent.com/44763264/224424304-d2e1c5a1-903b-47e4-819b-68ad9da25a78.png)

**Comment by aentin** [comment]
Исправлено
