### ISSUE TITLE
Не работает ссылка

### ISSUE THREAD

**Issue by SpxceCxt** [aentin/qgis-course#15]
7. Помимо добавленных слоёв, нам необходим слой для изображения океанов. К сожалению, из-за несовершенства QGIS вы не можете воспользоваться для этой цели набором данных с Natural Earth. Загрузите шейп-файл океанов по [этой ссылке](https://1drv.ms/u/s!AmtmZDq3JgxHgZswh2sFnErE-JEmGw?e=xoZW4c). Распакуйте шейп-файл в папку с другими шей-файлами и добавьте его в проект. 
Не работает ссылка на скачивание файла.

**Comment by SpxceCxt** [comment]
Файл: Ex02_MapWorld.Rmd

**Comment by SpxceCxt** [comment]
![изображение_2023-09-15_152709968](https://github.com/aentin/qgis-course/assets/105231450/325e4676-55da-47ba-88dc-7b05d232abc7)

**Comment by aentin** [comment]
Нерабочая ссылка исправлена, спасибо!
